/* Illustrative, read-only briefs. Never written to the live marketplace. */
window.ExampleTasks = [
  { title: 'Make customer feedback actionable.', company: 'Qadam Retail', industry: 'Retail', tags: ['Data analysis', 'Customer experience'], score: 96, need: 'Turn scattered customer reviews into a clear picture of what matters most, and what to improve next.', result: 'An interactive feedback dashboard and a prioritized set of recommendations.', users: ['Customer experience team'], data: 'An anonymized sample of customer reviews and support messages.', skills: ['Data analysis', 'Data visualization'], metric: 'Review categorization accuracy', target: 'At least 85%', verification: 'Compare a sample against manually labeled reviews.' },
  { title: 'A simpler first step into finance.', company: 'Tenge Lab', industry: 'Finance', tags: ['UX research', 'Product design'], score: 92, need: 'Help first-time users understand a budgeting app through a clearer, more welcoming onboarding experience.', result: 'A tested onboarding prototype with a short research report.', users: ['First-time budgeting app users'], data: 'Existing onboarding screens and anonymized usability notes.', skills: ['UX research', 'Prototyping'], metric: 'Onboarding completion', target: '4 out of 5 test participants', verification: 'Moderated usability sessions.' },
  { title: 'Less food waste. Better forecasts.', company: 'Dala Foods', industry: 'Food & beverage', tags: ['Machine learning', 'Python'], score: 88, need: 'Help a neighborhood bakery plan daily production using historical sales, so fewer good products go to waste.', result: 'A demand forecast prototype and an easy-to-use planning worksheet.', users: ['Bakery production planners'], data: 'Six months of anonymized daily product sales.', skills: ['Python', 'Forecasting'], metric: 'Forecast error', target: 'Below 20%', verification: 'Holdout evaluation on historical sales.' },
  { title: 'Bring local stories to a wider audience.', company: 'Steppe Studio', industry: 'Creative', tags: ['Marketing', 'Content strategy'], score: 85, need: 'Shape a focused content strategy that helps a small creative studio share its work with the right audience.', result: 'An audience research report and a four-week content plan.', users: ['Studio marketing team'], data: 'Public content archive and anonymized channel analytics.', skills: ['Marketing', 'Content strategy'], metric: 'Content plan approval', target: 'Four weeks of approved content', verification: 'Business review of the content plan.' },
  { title: 'Find the friction in last-mile delivery.', company: 'Jol Logistics', industry: 'Logistics', tags: ['Data analysis', 'Operations'], score: 78, need: 'Map where deliveries slow down and identify practical improvements for a small urban delivery operation.', result: 'A delivery performance dashboard and an improvement report.', users: ['Dispatch team'], data: 'Anonymized shipment and delivery timestamps.', skills: ['Data analysis', 'Process mapping'], metric: 'Bottleneck identification', target: 'Three actionable improvements', verification: 'Review with the operations team.' },
  { title: 'Make learning easier to navigate.', company: 'Bilim Space', industry: 'Education', tags: ['Product design', 'Web development'], score: 65, need: 'Explore a clearer course discovery experience for learners who are unsure where to start.', result: 'A clickable course discovery prototype.', users: ['New learners'], data: 'Current course catalog and navigation structure.', skills: ['Product design', 'Web development'], metric: 'Task completion', target: null, verification: null }
].map((item, index) => ({
  id: `example-${index + 1}`, is_example: true, status: 'published', business_name: item.company,
  published_at: `2026-09-${String(22 - index).padStart(2, '0')}T10:00:00Z`,
  card: {
    title: item.title, context: `An illustrative brief from ${item.company}, a fictional business.`, business_need: item.need,
    expected_result: item.result, industry: item.industry, tags: item.tags, target_users: item.users, required_skills: item.skills,
    available_data: { description: item.data, sources: ['Business-provided sample'], access_conditions: 'Shared with the selected team after a privacy review.' },
    limitations: ['Use anonymized data only.', 'Keep the work within the agreed prototype scope.'],
    success_criteria: [{ metric: item.metric, target: item.target, verification_method: item.verification }],
    business_contact: { name: null, role: 'Project owner', email: null },
    interaction_format: { channel: 'Video call', frequency: 'Weekly', feedback_process: 'Review a short progress update together.' },
    missing_information: [], warnings: []
  },
  evaluation: { score: item.score, readiness_level: item.score >= 90 ? 'priority' : item.score >= 70 ? 'ready' : 'working' }
}));
